use std::path::Path;

pub fn generate_extension_template(name: &str, output_dir: &Path) -> anyhow::Result<()> {
    let ext_dir = output_dir.join(name);
    std::fs::create_dir_all(ext_dir.join("src"))?;

    let cargo_toml = format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"
description = "A Writing Unicorns extension"

[lib]
crate-type = ["cdylib"]

[dependencies]
egui = "0.31"
"#
    );
    std::fs::write(ext_dir.join("Cargo.toml"), cargo_toml)?;

    let manifest_toml = format!(
        r#"[extension]
id = "author.{name}"
name = "{name}"
version = "0.1.0"
description = "My Writing Unicorns extension"
author = "Author"
repository = ""

[capabilities]
# File extensions this module handles, e.g. ["rs", "toml"]
languages = []
commands  = []
"#
    );
    std::fs::write(ext_dir.join("manifest.toml"), manifest_toml)?;

    let lib_rs = r#"//! Writing Unicorns Extension
//!
//! This extension was generated by Writing Unicorns.
//! Implement the Plugin trait methods you need.

use egui;

// Re-export the types you need from the IDE's plugin system.
// When the IDE loads your extension, it calls `create_plugin()`.

/// Token kinds for syntax highlighting
#[derive(Clone, Copy, PartialEq, Debug)]
pub enum TokenKind {
    Keyword,
    String,
    Comment,
    Number,
    Normal,
}

impl TokenKind {
    pub fn color(&self) -> egui::Color32 {
        match self {
            TokenKind::Keyword => egui::Color32::from_rgb(197, 134, 192),
            TokenKind::String => egui::Color32::from_rgb(206, 145, 120),
            TokenKind::Comment => egui::Color32::from_rgb(106, 153, 85),
            TokenKind::Number => egui::Color32::from_rgb(181, 206, 168),
            TokenKind::Normal => egui::Color32::from_rgb(212, 212, 212),
        }
    }
}

#[derive(Clone, Debug)]
pub struct Token {
    pub text: String,
    pub kind: TokenKind,
}

/// Your extension struct
pub struct MyExtension {
    // Add your state here
}

impl MyExtension {
    pub fn new() -> Self {
        Self {}
    }
}

// NOTE: The full Plugin trait requires the IDE's crate as a dependency.
// For now, implement this minimal interface that the IDE can call via FFI.

/// Called by the IDE to create your extension instance.
/// The returned pointer is cast to `Box<dyn Plugin>` by the loader.
#[no_mangle]
pub extern "C" fn create_plugin() -> *mut () {
    let boxed = Box::new(MyExtension::new());
    Box::into_raw(boxed) as *mut ()
}

/// Return the extension name (null-terminated C string)
#[no_mangle]
pub extern "C" fn plugin_name() -> *const std::ffi::c_char {
    b"my-extension\0".as_ptr() as *const std::ffi::c_char
}

/// Return the extension version
#[no_mangle]
pub extern "C" fn plugin_version() -> *const std::ffi::c_char {
    b"0.1.0\0".as_ptr() as *const std::ffi::c_char
}

/// Look up hover documentation for `word` in the provided file content.
/// Returns a heap-allocated C string (code-fenced signature), or null if not found.
/// Caller must free the result with `free_hover_info`.
///
/// # Safety
/// Both pointer arguments must be valid nul-terminated C strings.
#[no_mangle]
pub unsafe extern "C" fn hover_info_ffi(
    _word_ptr: *const std::ffi::c_char,
    _file_content_ptr: *const std::ffi::c_char,
) -> *mut std::ffi::c_char {
    // TODO: implement hover documentation for your language
    std::ptr::null_mut()
}

/// Return the LSP server command for this language extension.
/// Returns a heap-allocated JSON string like `["my-lsp","--stdio"]`, or null if not supported.
/// Caller must free the result with `free_hover_info`.
///
/// # Safety
/// The returned pointer must be freed with `free_hover_info`.
#[no_mangle]
pub extern "C" fn lsp_server_command_ffi() -> *mut std::ffi::c_char {
    // TODO: Return your language server command, e.g.:
    // Some(("my-language-server".to_string(), vec!["--stdio".to_string()]))
    std::ptr::null_mut()
}

/// Free a string returned by `hover_info_ffi`.
///
/// # Safety
/// `ptr` must have been returned by `hover_info_ffi` and not yet freed.
#[no_mangle]
pub unsafe extern "C" fn free_hover_info(ptr: *mut std::ffi::c_char) {
    if !ptr.is_null() {
        unsafe { drop(std::ffi::CString::from_raw(ptr)) }
    }
}
"#;
    std::fs::write(ext_dir.join("src").join("lib.rs"), lib_rs)?;

    let readme = format!(
        r#"# {name}

A Writing Unicorns extension.

## Implementing your extension

Edit `src/lib.rs` to implement the functionality you need. The template
provides a `MyExtension` struct and the required FFI entry points.

For syntax highlighting, populate a `Vec<Token>` from `tokenize_line` and
return it through the plugin interface once the Writing Unicorns SDK is
available.

## Building

```sh
cargo build --release
```

The compiled library will be at `target/release/lib{name}.so` (Linux),
`target/release/lib{name}.dylib` (macOS), or
`target/release/{name}.dll` (Windows).

## Installing in Writing Unicorns

Copy the compiled library **and** `manifest.toml` into the extensions directory:

```sh
EXT_DIR="$HOME/.config/writing-unicorns/extensions/author.{name}"
mkdir -p "$EXT_DIR"
cp target/release/lib{name}.so "$EXT_DIR/"
cp manifest.toml "$EXT_DIR/"
```

Writing Unicorns will pick up the extension on next launch (or when you
click **Reload Extensions** in the Extensions panel).

## manifest.toml format

```toml
[extension]
id = "author.{name}"        # unique reverse-domain ID
name = "{name}"             # human-readable name
version = "0.1.0"
description = "What your extension does"
author = "Your Name"
repository = "https://github.com/you/{name}"

[capabilities]
languages = ["rs", "toml"]  # file extensions this extension handles
commands  = ["my-command"]  # command palette entries
```

## Available capabilities

| Capability | Description |
|------------|-------------|
| `languages` | File extensions whose syntax highlighting this extension provides |
| `commands`  | Command palette entries contributed by this extension |
"#
    );
    std::fs::write(ext_dir.join("README.md"), readme)?;

    Ok(())
}
